### ISSUE TITLE
Workflow sample for BigQuery does not paginate through results

### ISSUE THREAD

**Issue by MarkEdmondson1234** [GoogleCloudPlatform/workflows-samples#122]
## Expected Behavior

The code from https://github.com/GoogleCloudPlatform/workflows-samples/blob/main/src/bigquery_pagetoken.workflows.yaml to allow you to page through BigQuery results as reported.  

Found code via https://cloud.google.com/workflows/docs/paginate-bigquery-results

## Actual Behavior

The code sample uses `googleapis.bigquery.v2.jobs.query` instead of `googleapis.bigquery.v2.jobs.insert` so it creates a synchronous BigQuery API call, returning all rows which overflows Workflows execution if of any size.

## Steps to Reproduce the Problem

1. Run code on https://github.com/GoogleCloudPlatform/workflows-samples/blob/main/src/bigquery_pagetoken.workflows.yaml with a large BigQuery table

## Fix

I replaced the code with `googleapis.bigquery.v2.jobs.insert` and it worked:

```yaml

    - startQuery:
        call: googleapis.bigquery.v2.jobs.insert
        args:
            projectId: ${projectId}
            body:
                configuration:
                    query:
                        useLegacySql: false
                        query: ${bq_query}
```
