### ISSUE TITLE
Sample code for BigQuery pagination fails execution if query limit is removed 

### ISSUE THREAD

**Issue by jbergeskans** [GoogleCloudPlatform/workflows-samples#160]
## Expected Behavior
Removing the LIMIT statement from the [example code](https://github.com/GoogleCloudPlatform/workflows-samples/blob/main/src/bigquery_pagetoken.workflows.yaml#L29) should allow for Workflows to iterate through all the results in the example table via pagination, thus circumventing the memory limit of Workflows.

## Actual Behavior
When removing the LIMIT statement, the workflow execution fails with the following error message:
```
HTTP response exceeded the limit of 2097152 bytes
in step "startQuery", routine "main", line: 8
{
  "message": "HTTP response exceeded the limit of 2097152 bytes",
  "tags": [
    "ValueError"
  ]
}
```

## Steps to Reproduce the Problem
Run the following workflows code:
```
main:
  params: [input]
  steps:
    - init:
        assign:
          - pageToken: null
    - startQuery:
        call: googleapis.bigquery.v2.jobs.query
        args:
          projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          body:
            useLegacySql: false
            # Remove LIMIT from the query to iterate through all results
            query: SELECT name, SUM(number) AS total FROM `bigquery-public-data.usa_names.usa_1910_2013` GROUP BY name ORDER BY total DESC
        result: query
    - getPage:
        call: googleapis.bigquery.v2.jobs.getQueryResults
        args:
          projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          jobId: ${query.jobReference.jobId}
          maxResults: 10
          pageToken: ${pageToken}
        result: page
    - processPage:
        for:
          value: row
          in: ${page.rows}
          steps:
            - processRow:
                call: sys.log
                args:
                  data: ${row}
    - checkIfDone:
        switch:
          - condition: ${"pageToken" in page and page.pageToken != ""}
            assign:
              - pageToken: ${page.pageToken}
            next: getPage
```

## Fix
The example code needs to be updated to use the endpoint `googleapis.bigquery.v2.jobs.insert` (with a config block etc.) instead of `googleapis.bigquery.v2.jobs.query` as the insert endpoint returns a job object instead of the full results.

Suggestion (YAML, but JSON example also needs to be updated)
```
main:
  params: [input]
  steps:
    - init:
        assign:
          - pageToken: null
    - startQuery:
        call: googleapis.bigquery.v2.jobs.insert
        args:
          projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          body:
            configuration:
              query: 
                useLegacySql: false
                # Remove LIMIT from the query to iterate through all results
                query: SELECT name, SUM(number) AS total FROM `bigquery-public-data.usa_names.usa_1910_2013` GROUP BY name ORDER BY total DESC LIMIT 50
        result: query
    - getPage:
        call: googleapis.bigquery.v2.jobs.getQueryResults
        args:
          projectId: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          jobId: ${query.jobReference.jobId}
          maxResults: 10
          pageToken: ${pageToken}
        result: page
    - processPage:
        for:
          value: row
          in: ${page.rows}
          steps:
            - processRow:
                call: sys.log
                args:
                  data: ${row}
    - checkIfDone:
        switch:
          - condition: ${"pageToken" in page and page.pageToken != ""}
            assign:
              - pageToken: ${page.pageToken}
            next: getPage
```
