### ISSUE TITLE
Can't access result of Cloud Build Connector

### ISSUE THREAD

**Issue by sano307** [GoogleCloudPlatform/workflows-samples#30]
## Expected Behavior

The value set in the result of Cloud Build Connector is accessible from the next step.

## Actual Behavior

```sh
Invalid value for "vars" parameter: vars map does not contain key "resp"
```

## Steps to Reproduce the Problem

```yaml
main:
  params: [args]
  steps:
  - init:
      assign:
        - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}

  - setup:
      call: googleapis.cloudbuild.v1.projects.builds.create
      args:
        projectId: ${project_id}
        body:
          source:
            repoSource:
              repoName: xxx
              branchName: main
          steps:
          - name: "ubuntu"
            args: echo $SHORT_SHA > $BUILDER_OUTPUT/output
      result: resp

  - check:
      return: ${resp}
```

## Specifications

- Version: Google Provider v3.70.0
- Platform: Terraform v0.12.31
