### ISSUE TITLE
Is exists a built-in function that makes sys.now() into timestamp format?

### ISSUE THREAD

**Issue by sano307** [GoogleCloudPlatform/workflows-samples#38]
I want to create a document of Cloud Firestore, and containing the timestamp value. but, there isn't such a function that converts a floating value(`sys.now`) to timestamp format. Doesn't the function that plays the same role as below `datetime.timestamp()` exist?

Thank you.

## Sample

```yaml
main:
  params: [args]
  steps:
  - init:
      assign:
        - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}

  - test_firestore:
      call: googleapis.firestore.v1.projects.databases.documents.createDocument
      args:
        parent: ${"projects/" + project_id + "/databases/(default)/documents/xxx"}
        collectionId: yyy
        documentId: xxx-yyy
        body:
          fields:
            name:
              stringValue: kim
            created_at:
              timestampValue: ${datetime.timestamp(sys.now, 'JST')}
      result: resp

  - check:
      return: ${resp}
```
