### ISSUE TITLE
Add a sample for googleapis.bigquery.v2.jobs.query and queryParameters use case

### ISSUE THREAD

**Issue by matButez** [GoogleCloudPlatform/workflows-samples#64]
## Expected Behavior
Could you please add a sample for bigquery request using queryParameters[] and googleapis.bigquery.v2.jobs.query  ? 

After many tries, i'm still not able to use a query with a variable named : @table_suffix.

My query is quite simple as we can do using an other client library :

```
        const sqlQuery = `SELECT * FROM \`project_id.dataset.*\` WHERE _TABLE_SUFFIX = @table_suffix LIMIT 5`;

        const options = {
            query: sqlQuery,
            location: 'EU',
            params: { table_suffix: 'events_intraday_20211202' },
        };
```

if i follow the snippet i should use "queryParameters" parameters but if i check the documentation of the object "QueryRequest" i should use queryParameters[]
https://cloud.google.com/workflows/docs/reference/googleapis/bigquery/v2/jobs/query#subworkflow_snippet
https://cloud.google.com/workflows/docs/reference/googleapis/bigquery/v2/Overview#queryrequest

I try this 
```
- init:
    assign:
    - table_suffix: "events_intraday_20211202"
    - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
    - query: "SELECT * FROM `project_id.dataset.*` WHERE _TABLE_SUFFIX = @table_suffix LIMIT 5"

- query:
    call: googleapis.bigquery.v2.jobs.query
    args:
        projectId: ${project_id}
        body:
            query: ${query}
            useLegacySql: false
            queryParameters[]: 
                name: "table_suffix"
                parameterType:
                    type: "string"
                parameterValue:
                    value: "events_intraday_20211202"
    result: queryResult
- documentFound:
    return: ${queryResult}
```

I will appreciate your help.

**Comment by matButez** [comment]
Finally, found it. 

Could probably help others with same question.

```
- query:
    call: googleapis.bigquery.v2.jobs.query
    args:
        projectId: ${project_id}
        body:
            query: ${query}
            useLegacySql: false
            queryParameters: 
                - 
                    name: "table_suffix"
                    parameterType:
                        type: "STRING"
                    parameterValue: 
                        value: "events_intraday_20211202"
    result: queryResult
```
